version: '3.8'

services:
  tuition-service:
    build: 
      context: ./tuition-service 
      dockerfile: Dockerfile.dev
    volumes:
      - ./tuition-service:/app
      - ./.m2cache:/root/.m2
    command: ["mvn", "spring-boot:run"]
    ports: 
      - "8081:8081"

  payment-processor-service:
    build: 
      context: ./payment-processor-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./payment-processor-service:/app
      - ./.m2cache:/root/.m2
    command: ["mvn", "spring-boot:run"]
    ports: 
      - "8082:8082"

  customer-account-service:
    build: 
      context: ./customer-account-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./customer-account-service:/app
      - ./.m2cache:/root/.m2
    command: ["mvn", "spring-boot:run"]
    ports: 
      - "8083:8083"